export const COMMON_POST_TAGS = [
  "Technology",
  "Programming",
  "Web Development",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Startups",
  "Entrepreneurship",
  "Productivity",
  "Career",
  "Remote Work",
  "Leadership",
  "Design",
  "UI/UX",
  "Mobile Development",
  "DevOps",
  "Cloud",
  "Cybersecurity",
  "Open Source",
  "Databases",
  "API Design",
  "Testing",
  "System Design",
  "Finance",
  "Investing",
  "Personal Finance",
  "Economics",
  "Marketing",
  "Content Strategy",
  "Social Media",
  "Education",
  "Learning",
  "Self Improvement",
  "Psychology",
  "Health",
  "Fitness",
  "Nutrition",
  "Travel",
  "Lifestyle",
  "Culture",
  "Books",
  "Movies",
  "Music",
  "Gaming",
] as const;
